name: CRTO Lab Status

on:
    push:
        branches: [main]
    schedule:
        - cron: '*/50 * * * *'


jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Check out source code
              uses: actions/checkout@v4

            - name: Set up Python 3.10
              uses: actions/setup-python@v3
              with:
                python-version: "3.10"
        
            - name: Install python dependencies
              run: |
                python -m pip install --upgrade pip
                if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

            # - name: Install headless chrome
            #   run: |
            #     sudo apt-get -y update
            #     sudo apt-get install -y google-chrome-stable
            
            - name: Run the script
              run: python crto.py
              env:
                EMAIL: ${{ secrets.EMAIL }}
                PASSWORD: ${{ secrets.PASSWORD }}
                WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
